Add Dockerfile for JDK 20 on Red Hat UBI 9
jboss-dockerfiles/wildfly pull request #176
Opened 2023-05-03 21:57 UTC by cam-rod

- Splitting the current Dockerfile into two: <= JDK 19 (on CentOS 7) and >= JDK 20 (on Red Hat UBI 9) 
  - They don't really support swappable base images ([buildah](https://github.com/containers/buildah) would work better for that), so the solution here is a multi-stage build, with the first stage validating that the JDK matches the file bounds. The stage isn't necessary, but makes for a decent sanity check.
- Updated the CI action by splitting it into CentOS and UBI jobs. Same as above, there isn't an easy way to filter a matrix of JDK versions without switching off Dockerfiles entirely.

2023-05-04 06:41 UTC, jmesnil commented
you could make the suffix of the base image (`-centos7` & `-ubi9`) a `dist` ARG to continue to use a single Dockerfile with the base image being eclipse-temurin:${jdk}-{dist}

Then in the github action, you only need to associate the jdk versions with the dist (eg using env var):

* `11, 17, 19` -> `centos7`
* `20` -> `ubi9`

2023-05-04 06:49 UTC, jmesnil commented
You should have a look at https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrixinclude to replace:

```
strategy:
  matrix:
    jdk-version: [11, 17]
```

with:

```
strategy:
  matrix:
    include:
      - jdk-version: 11
        dist: centos7
      - jdk-version: 17
        dist: centos7
      - jdk-version: 20
        dist: ubi9
```

(I've not tested it)

2023-05-04 16:54 UTC, cam-rod commented
made the suggested changes, let me know what you think

2023-05-04 17:01 UTC, jmesnil requested changes

2023-05-04 17:16 UTC, cam-rod commented on Dockerfile
> +FROM ubi9-minimal as jdk-filter
yeah, I can drop this

2023-05-05 06:49 UTC, jmesnil approved these changes

2023-05-05 06:49 UTC, merged

2023-05-05 06:49 UTC, jmesnil commented
@cam-rod thanks