Request to build and release images for s390x
jboss-dockerfiles/wildfly pull request #178
Opened 2023-06-19 10:23 UTC by namrata-ibm

Changes included in this PR:
1. Updated base image to `eclipse-temurin:ubi9-minimal` considering it supports multiple archs. Also centos 7 will reach its [end of life](https://www.redhat.com/en/events/webinar/centos-linux-reaching-its-end-life-now-what#:~:text=Updates%20and%20releases%20of%20CentOS,7%20on%20June%2030%2C%202024) down the line. Wanted to understand whether this change would have any major impact on existing users?
2. Added s390x to jdk 11 & 17 matrix as jdk 20 is `not yet` available for s390x.

Resolves #173

2023-06-19 10:24 UTC, namrata-ibm commented
@jmesnil could you please share your thoughts?

2024-05-02 06:58 UTC, jmesnil requested changes
@namrata-ibm sorry for the late reply

I've recently updated WildFly Docker image to produce a JDK21 variant on ubi9-minimal that supports s390x.

Could you update your PR to rebase and add the `linux/s390x` platform for this JDK version?

I'd prefere to postpone the switch from centos7 to ubi9-minimal after it's communicated to our community with the impeding end of line of CentOS 7.

However, I see no issue with respiring our latest WildFly 32 images to add s390x support to their JDK 21 variants.

2024-05-30 09:24 UTC, namrata-ibm commented
@jmesnil I have updated PR with your suggestions. Could you please have a look? 
Thank you very much for your support.

2024-05-30 09:35 UTC, jmesnil approved these changes

2024-05-30 09:35 UTC, merged

2024-05-30 09:36 UTC, jmesnil commented
@namrata-ibm thanks!

2024-05-31 06:40 UTC, jmesnil commented
@namrata-ibm I've released new image tags with support for s390x: `quay.io/wildfly/wildfly:latest-jdk21`

Could you please try them to make sure they run as expected? Thanks for you contribution!

2024-05-31 08:56 UTC, namrata-ibm commented
Hi @jmesnil I have verified that latest/latest-jdk21 images work as expected on s390x. 
Thank you very much for your support.